# Generated by Django 4.2.5 on 2023-10-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('restaurant_type', models.CharField(max_length=120)),
                ('price_range', models.PositiveSmallIntegerField(choices=[(1, '$'), (2, '$$'), (3, '$$$'), (4, '$$$$'), (5, '$$$$$')], default=1)),
                ('food_type', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('delivers', models.BooleanField()),
            ],
        ),
    ]
